apiVersion: v1
kind: Service
metadata:
  name: nginx-internal-svc
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: echo
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
  - port: 443
    protocol: TCP
  selector:
    app: nginx-pod